import { SQLiteDatabase } from "expo-sqlite";

// const productNames: string[] = [
//   "Arroz",
//   "Feijão",
//   "Macarrão",
//   "Açucar",
//   "Sal",
//   "Óleo de soja",
//   "Café",
//   "Leite",
//   "Farinha de trigo",
//   "Farinha de mandioca",
//   "Pão de forma",
//   "Biscoito",
//   "Manteiga",
//   "Margarina",
//   "Queijo",
//   "Presunto",
//   "Ovos",
//   "Batata",
//   "Cebola",
//   "Alho",
//   "Tomate",
//   "Cenoura",
//   "Beterraba",
//   "Abobrinha",
//   "Chuchu",
//   "Alface",
//   "Couve",
//   "Espinafre",
//   "Repolho",
//   "Maça",
//   "Banana",
//   "Laranja",
//   "Mamão",
//   "Melancia",
//   "Uva",
//   "Pera",
//   "Abacaxi",
//   "Limão",
//   "Morango",
//   "Iogurte",
//   "Requeijão",
//   "Creme de leite",
//   "Leite condensado",
//   "Molho de tomate",
//   "Extrato de tomate",
//   "Milho verde",
//   "Ervilha",
// ];

export const productNames = [
  { id: 1, name: "Arroz" },
  { id: 2, name: "Feijão" },
  { id: 3, name: "Macarrão" },
  { id: 4, name: "Açucar" },
  { id: 5, name: "Sal" },
  { id: 6, name: "Óleo de soja" },
  { id: 7, name: "Café" },
  { id: 8, name: "Leite" },
  { id: 9, name: "Farinha de trigo" },
  { id: 10, name: "Farinha de mandioca" },
  { id: 11, name: "Pão de forma" },
  { id: 12, name: "Biscoito" },
  { id: 13, name: "Manteiga" },
  { id: 14, name: "Margarina" },
  { id: 15, name: "Queijo" },
  { id: 16, name: "Presunto" },
  { id: 17, name: "Ovos" },
  { id: 18, name: "Batata" },
  { id: 19, name: "Cebola" },
  { id: 20, name: "Alho" },
  { id: 21, name: "Tomate" },
  { id: 22, name: "Cenoura" },
  { id: 23, name: "Beterraba" },
  { id: 24, name: "Abobrinha" },
  { id: 25, name: "Chuchu" },
  { id: 26, name: "Alface" },
  { id: 27, name: "Couve" },
  { id: 28, name: "Espinafre" },
  { id: 29, name: "Repolho" },
  { id: 30, name: "Maça" },
  { id: 31, name: "Banana" },
  { id: 32, name: "Laranja" },
  { id: 33, name: "Mamão" },
  { id: 34, name: "Melancia" },
  { id: 35, name: "Uva" },
  { id: 36, name: "Pera" },
  { id: 37, name: "Abacaxi" },
  { id: 38, name: "Limão" },
  { id: 39, name: "Morango" },
  { id: 40, name: "Iogurte" },
  { id: 41, name: "Requeijão" },
  { id: 42, name: "Creme de leite" },
  { id: 43, name: "Leite condensado" },
  { id: 44, name: "Molho de tomate" },
  { id: 45, name: "Extrato de tomate" },
  { id: 46, name: "Milho verde" },
  { id: 47, name: "Ervilha" },
];

// export async function seed(database: SQLiteDatabase) {
//   await database.withTransactionAsync(async () => {
//     for (const name of productNames) {
//       await database.runAsync("INSERT INTO products (name) VALUES (?);", [name]);
//     };
//   });
// };